### ISSUE TITLE
Plejd Devices became unavailable

### ISSUE THREAD

**Issue by vegarnaess** [emilohman/homey-plejd#51] opened 2023-05-25 07:52 UTC
Hi,

Have 26 Plejd devices connected to HP23 without hub. Has worked fine for 3 days but suddenly all devices became unavailable. 
Diagnostic report: 1b9cc41b-399b-4f21-b47b-6b70c7770075

**Comment by gorper** [comment] 2023-06-02 22:05
I recognise this homey 2023 pro, if I run flow with more than 1 plejd then all plejd units get 🔺 sign, if clicked, an error pops up “connecting to BLE mesh”. Most often successful after a while. Anyhow if I utilise delay so every plejd in the flow run alone then it works. I guess it chokes the BLE when multiple ones command is sent and homey gets thrown out of plejd mesh. I also recognise issue 52.

**Comment by kaarigstad** [comment] 2023-07-02 16:54
I observe the same issue as @gorper. A single switch works fine, but when there are more than one (ie. turn of all lights in a room) it manages to turn of one and then crashes. The problem is consistent and happens every time I try to turn of more than one switch. Everything works as it should in the Plejd app.

**Comment by emilohman** [comment] 2023-11-22 11:52
Should be fixed in version 3.3.6, released today. Please try it out.

**Comment by kaarigstad** [comment] 2023-11-25 17:47
I can confirm this issue seems to be solved after upgrade to 3.3.6.

**Closed** 2023-12-04 12:02 UTC
